server:
  port: 8000
video:
  title: 30
spring:
  application:
    name: xdclass-order-service
#  zipkin:
#    base-url: http://39.100.71.133:9411/ #zipkin地址
#    discovery-client-enabled: false  #不用开启服务发现
#    sleuth:
#      sampler:
#        probability: 1.0 #采样百分比
#  cloud:
#    sentinel:
#      transport:
#        dashboard: 127.0.0.1:8180
#        port: 9999

    nacos:
      discovery:
        server-addr: 39.100.71.133:8848
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://39.100.71.133:33061/cloud_order?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: 123456
# 控制台输出sql、下划线转驼峰
mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true

#使用随机负载均衡策略
xdclass-video-service:
  ribbon:
    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule

  # Redis 配置
  redis:
    # Redis 服务器地址
    host: 39.100.71.133
    # 连接端口号
    port: 6380
    # 数据库索引（0 - 15）
    database: 0
    # 连接超时时间（毫秒）
    timeout: 10000
    # lettuce 参数
    lettuce:
      pool:
        # 最大连接数(使用负值表示没有限制) 默认为 8
        max-active: 10
        # 最大阻塞等待时间(使用负值表示没有限制) 默认为 -1 ms
        max-wait: -1
        # 最大空闲连接 默认为 8
        max-idle: 5
        # 最小空闲连接 默认为 0
        min-idle: 0